### ISSUE TITLE
Configure shared secrets

### ISSUE THREAD

**Issue by schanzen** [reclaimID/demo#9]
The HTTP Basic authentication against the OpenID Connect IdP and the JWTs use a hard-coded shared secret.
This secret just happens to be the default for the IdP (in the runtime).
The shared secret should be configurable (as an ENV variable) for both the demo and the runtime.

See:
- target/demo.rb (in demo); "secret" is hardcoded
- gnunet-config -s reclaim-rest-plugin -o PSW
- gnunet-config -s reclaim-rest-plugin -o JWT_SECRET

**Comment by schanzen** [comment]
The "PSW" is the secret used for HTT Basic
The "JWT_SECRET" is used for the JWT HMAC

**Comment by kiliant** [comment]
added commit https://github.com/reclaimID/client/commit/6fb1bdc4c4ca375aa6ce020e06c94ced7eb5e44e. but there is a bug. when i set both files `.tmp/psw_secret` and `.tmp/jwt_secret` to "secret", all is working good. but when the auto generated values are in place, validation fails.
`docker exec reclaim-runtime gnunet-config -s reclaim-rest-plugin -o JWT_SECRET` reveals that JWT and PSW are set correctly, respectively.
any idea where this might break @schanzen?

**Comment by schanzen** [comment]
in demo the variables are not used. at least in the pushed master.On 5 Dec 2018 10:11 AM, "Thomas A. Kilian" <notifications@github.com> wrote:added commit reclaimID/client@6fb1bdc. but there is a bug. when i set both files .tmp/psw_secret and .tmp/jwt_secret to "secret", all is working good. but when the auto generated values are in place, validation fails.
docker exec reclaim-runtime gnunet-config -s reclaim-rest-plugin -o JWT_SECRET reveals that JWT and PSW are set correctly, respectively.
any idea where this might break @schanzen?

**Comment by kiliant** [comment]
sorry, is committed now

**Comment by kiliant** [comment]
this has been fixed in https://github.com/reclaimID/runtime/commit/468dfed1d7a168ef7986658816ae9474f6659a21
